name: Analyze and Compare lflist.conf

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  analyze-file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout this repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Run Node.js script
      env: 
        TOKEN: ${{ secrets.DEST_REPO_TOKEN }}  # Pasar el token como variable de entorno
      run: node scripts/script.js

    - name: Upload result as artifact
      uses: actions/upload-artifact@v3
      with:
        name: lflist-analysis
        path: scripts/lflist.conf



